#makefile for CMD1

all: test

CXX = g++
CXXFLAGS = -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

OBJS = test_text.o rooms.o player.o item.o
SRCS = test_text.cpp rooms.cpp player.cpp item.cpp
HEADERS = rooms.hpp player.hpp item.hpp

test: ${OBJS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${OBJS} -o test_text

${OBJS}: ${SRCS}
	${CXX} ${CXXFLAGS} -c $(@:.o=.cpp)

